// Single place where the UI resolves its document elements. Every module
// receives the returned object rather than querying the document itself, which
// keeps the element ids in one list and lets the headless tests stub the DOM
// once.
export function queryUiElements() {
  return {
    tableHead: document.querySelector("#mem-table thead"),
    tableBody: document.querySelector("#mem-table tbody"),
    channelEditorEl: document.querySelector("#channel-editor"),
    settingsEditorEl: document.querySelector("#settings-editor"),
    viewChannelsEl: document.querySelector("#view-channels"),
    viewSettingsEl: document.querySelector("#view-settings"),
    settingsTabsEl: document.querySelector("#settings-tabs"),
    settingsSummaryEl: document.querySelector("#settings-summary"),
    settingsEmptyEl: document.querySelector("#settings-empty"),
    settingsContentEl: document.querySelector("#settings-content"),
    fileInput: document.querySelector("#csv-file"),
    imgFileInput: document.querySelector("#img-file"),
    debugOutputEl: document.querySelector("#debug-output"),
    reportIssueEl: document.querySelector("#report-issue"),
    serialSupportWarningEl: document.querySelector("#webserial-support-warning"),
    liveRadioSupportWarningEl: document.querySelector("#live-radio-support-warning"),
    radioSearchEl: document.querySelector("#radio-search"),
    radioSearchResultsEl: document.querySelector("#radio-search-results"),
    radioMakeEl: document.querySelector("#radio-make"),
    radioModelEl: document.querySelector("#radio-model"),
    serialConnectToggleEl: document.querySelector("#serial-connect-toggle"),
    webusbConnectToggleEl: document.querySelector("#serial-connect-webusb"),
    radioDownloadEl: document.querySelector("#radio-download"),
    radioUploadEl: document.querySelector("#radio-upload"),
    cloneProgressEl: document.querySelector("#clone-progress"),
    cloneProgressBarEl: document.querySelector("#clone-progress-bar"),
    cloneProgressLabelEl: document.querySelector("#clone-progress-label"),
    cloneProgressPercentEl: document.querySelector("#clone-progress-percent"),
    channelInsertEl: document.querySelector("#channel-insert"),
    channelRemoveEl: document.querySelector("#channel-remove"),
    channelMoveUpEl: document.querySelector("#channel-move-up"),
    channelMoveDownEl: document.querySelector("#channel-move-down"),
    channelCopyEl: document.querySelector("#channel-copy"),
    channelCutEl: document.querySelector("#channel-cut"),
    channelPasteEl: document.querySelector("#channel-paste"),
    channelMenuToggleEl: document.querySelector("#channel-menu-toggle"),
    channelMenuPopupEl: document.querySelector("#channel-menu-popup"),
    channelAddGmrsEl: document.querySelector("#channel-add-gmrs"),
    channelAddFrsEl: document.querySelector("#channel-add-frs"),
    channelAddPmr446El: document.querySelector("#channel-add-pmr446"),
    channelImportPrzemiennikiEl: document.querySelector("#channel-import-przemienniki"),
    channelImportRepeaterbookEl: document.querySelector("#channel-import-repeaterbook"),
    przemiennikiModalEl: document.querySelector("#przemienniki-modal"),
    przemiennikiFormEl: document.querySelector("#przemienniki-form"),
    przemiennikiModalTitleEl: document.querySelector("#przemienniki-modal-title"),
    przemiennikiCountryEl: document.querySelector("#przemienniki-country"),
    przemiennikiBandListEl: document.querySelector("#przemienniki-band-list"),
    przemiennikiModeListEl: document.querySelector("#przemienniki-mode-list"),
    przemiennikiOnlyWorkingEl: document.querySelector("#przemienniki-onlyworking"),
    przemiennikiLatitudeEl: document.querySelector("#przemienniki-latitude"),
    przemiennikiLongitudeEl: document.querySelector("#przemienniki-longitude"),
    przemiennikiRangeEl: document.querySelector("#przemienniki-range"),
    przemiennikiGeolocateEl: document.querySelector("#przemienniki-geolocate"),
    przemiennikiCancelEl: document.querySelector("#przemienniki-cancel"),
    importChoiceModalEl: document.querySelector("#import-choice-modal"),
    importChoiceMessageEl: document.querySelector("#import-choice-message"),
    importChoiceReplaceEl: document.querySelector("#import-choice-replace"),
    importChoiceMergeEl: document.querySelector("#import-choice-merge"),
    importChoiceCancelEl: document.querySelector("#import-choice-cancel"),
    sidebarControlEls: Array.from(
      document.querySelectorAll(".left-panel select, .left-panel button, .left-panel input"),
    ),
  };
}
