"""The JS globals Pyodide exposes to ``runtime_bridge`` as the ``js`` module.

These are not Python functions: each is a browser-side function installed on
``globalThis`` by ``web/js/runtime-rpc.js`` before the runtime boots, reached
through Pyodide's ``js`` proxy module. Pyright cannot see across that boundary,
so the bridge contract is declared here instead — which also makes this file
the one place the JS and Python halves of the serial bridge are written down
together.

Everything returns ``Any``: the values arrive as ``JsProxy`` objects (awaitable
for the async ones), and ``_js_to_py()`` is what converts them.
"""

from typing import Any

# Fetches a CHIRP source file into the Pyodide filesystem during boot.
def fetch_chirp_source(path: str) -> Any: ...

# Serial transport. The async ones resolve to a JsProxy result object.
def serial_open(baudrate: int) -> Any: ...
def serial_close() -> Any: ...
def serial_read_bytes(count: int, timeout_ms: int) -> Any: ...
def serial_read_hex(count: int, timeout_ms: int) -> Any: ...
def serial_write_bytes(data: Any) -> Any: ...
def serial_write_hex(hex_text: str) -> Any: ...

# Clone-session preparation: buffer clear, control lines, settle delay.
def serial_prepare_clone(*args: Any, **kwargs: Any) -> Any: ...
def serial_reset_buffers() -> Any: ...

# Mid-clone DTR/RTS changes. ``None`` leaves that line untouched.
def serial_set_signals(dtr: bool | None, rts: bool | None) -> Any: ...

# Diagnostics and clone progress, surfaced in the app's debug panel.
def serial_log(message: str) -> Any: ...
def serial_progress(cur: int, max: int, message: str) -> Any: ...
